require('corey-collins.lspconfig')
require('corey-collins.treesitter')
require('corey-collins.nvimcmp')
require('corey-collins.autopairs')
-- require('corey-collins.trouble')
require('corey-collins.dapui')
require('corey-collins.rustaceanvim')
require('corey-collins.keymaps')
require('corey-collins.toggleterm')
require('corey-collins.nvimtree')
require('corey-collins.virtualtext')
