require('corey-collins.lspconfig')
require('corey-collins.treesitter')
require('corey-collins.nvimcmp')
-- require('corey-collins.trouble')
require('corey-collins.keymaps')
require('corey-collins.toggleterm')
require('corey-collins.nvimtree')
