-- Trouble is now configured in lazy.lua
-- Keybindings:
--   <leader>xx - Toggle diagnostics
--   <leader>xX - Toggle buffer diagnostics
--   <leader>cs - Toggle symbols
--   <leader>cl - Toggle LSP references
